language: cpp
env:
  global:
    - PYENV_ROOT=$HOME/.pyenv
    - QMAKE_EXTRA="PYTHONQTALL_CONFIG=PythonQtCore PYTHONQTALL_CONFIG+=PythonQtGui CONFIG+=tests CONFIG+=noPch CONFIG+=ccache CONFIG+=generator"
cache:
  timeout: 1000
  apt: true
  ccache: true
  pip: true
  directories:
    - $PYENV_ROOT
addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3-dev
    - qtbase5-private-dev
  homebrew:
    update: true
    packages:
    - qt
    - python3
    - ccache
matrix:
  include:
  - os: linux
    distro: xenial
    env: QMAKE_EXTRA="$QMAKE_EXTRA CONFIG+=debug CONFIG+=sanitizer CONFIG+=sanitize_address CONFIG+=sanitize_undefined"
    name: Linux debug + vera
  - os: osx
    name: macOS release
    env: QMAKE_EXTRA="$QMAKE_EXTRA CONFIG+=no-sanitizers CONFIG+=release"
git:
  depth: 1

#before_install:

#install:
#- "./.travis/install.sh"

script:
- export PATH="/usr/local/opt/qt/bin:$PATH"
- qmake -qt=5 -v
- g++ --version
- ccache -sz
- qmake -qt=5 -r $QMAKE_EXTRA
- make -j 2
- bin/PythonQtTest
- bin/pythonqt_generator --help
after_script:
- ccache -s
