language: cpp
env:
  global:
    - PYENV_ROOT=$HOME/.pyenv
    - QMAKE_EXTRA="CONFIG+=tests CONFIG+=noPch CONFIG+=ccache CONFIG+=generator"
cache:
  timeout: 1000
  apt: true
  ccache: true
  pip: true
  directories:
    - $PYENV_ROOT
addons:
  apt:
    update: true
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - python3-dev
    - qtbase5-private-dev
  homebrew:
    update: false
    packages:
    - qt
    - python3
matrix:
  include:
  - os: linux
    services: docker
    name: Linux release
  - os: linux
    services: docker
    env: CONFIG=debug     VERA=true SUFFIX=-d
    name: Linux debug + vera
  - os: osx
    name: macOS release
    env: QMAKE_EXTRA="$QMAKE_EXTRA CONFIG+=no-sanitizers"
git:
  depth: 1

#before_install:

#install:
#- "./.travis/install.sh"

script:
- qmake -v
- g++ --version
- ccache -sz
- qmake -r $QMAKE_EXTRA
- make -j 2

after_script:
- ccache -s
