language: minimal
sudo: false
env:
  global:
    - CCACHE_SLOPPINESS=include_file_ctime,include_file_mtime
    - QMAKE_EXTRA="PYTHONQTALL_CONFIG=PythonQtCore PYTHONQTALL_CONFIG+=PythonQtGui CONFIG+=tests CONFIG+=noPch CONFIG+=ccache CONFIG+=generator"
cache:
  timeout: 1000
  apt: true
  ccache: true
  pip: true
  directories:
    - $PYENV_ROOT
    - $HOME/Library/Caches/Homebrew
    - /usr/local/Homebrew

matrix:
  include:
  - os: linux
    dist: xenial
    env: QMAKE_EXTRA="$QMAKE_EXTRA CONFIG+=debug CONFIG+=sanitizer CONFIG+=sanitize_address CONFIG+=sanitize_undefined"
    name: Xenial debug
    addons:
      apt:
        packages:
        - qtbase5-private-dev
        - qt5-default
        - python3-dev
        - g++
  - os: linux
    dist: bionic
    env: QMAKE_EXTRA="PYTHON3_VERSION_MINOR=8 $QMAKE_EXTRA QMAKE_CXX=g++-9 QMAKE_LINK=g++-9 CONFIG+=debug CONFIG+=sanitizer CONFIG+=sanitize_address CONFIG+=sanitize_undefined"
    name: 'Bionic debug Python 3.8 + GCC-9'
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test # g++-9
        - deadsnakes # python3.8
        packages:
        - qtbase5-private-dev
        - qt5-default
        - g++-9
        - python3.8-dev

  - os: osx
    name: macOS release
    env: QMAKE_EXTRA="$QMAKE_EXTRA CONFIG+=no-sanitizers CONFIG+=release"
    addons:
      homebrew:
        update: true # `brew bundle` fails otherwise
        packages:
        - qt
        - python3
        - ccache
git:
  depth: 1

before_cache:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then brew cleanup; fi
# Credit https://discourse.brew.sh/t/best-practice-for-homebrew-on-travis-brew-update-is-5min-to-build-time/5215/9
# Cache only .git files under "/usr/local/Homebrew" so "brew update" does not take 5min every build
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then find /usr/local/Homebrew \! -regex ".+\.git.+" -delete; fi

#before_install:

#install:
#- "./.travis/install.sh"

script:
- export PATH="/usr/local/opt/qt/bin:/usr/local/opt/python/libexec/bin:$PATH"
- export PKG_CONFIG_PATH="$(python-config --prefix)/lib/pkgconfig"
- pkg-config --list-all
- qmake -v
- python --version
- g++ --version
- ccache -sz
- qmake -r $QMAKE_EXTRA
- make -j 2
- export ASAN_OPTIONS=detect_leaks=0
- export LD_LIBRARY_PATH=$PWD/bin
- export DYLD_LIBRARY_PATH=$LD_LIBRARY_PATH
- bin/PythonQtTest -platform minimal
- if [ -x generator/pythonqt_generator ] ; then generator/pythonqt_generator --help ; fi

after_script:
- ccache -s
- find .
